# Inspired by a cmake script in opencv
#
configure_file(${PROJECT_SOURCE_DIR}/include/jgr/sys/version.h ${PROJECT_BINARY_DIR}/version.tmp)

file(STRINGS ${PROJECT_BINARY_DIR}/version.tmp JGR_SYS_VERSION_MAJOR_LINE REGEX "JGR_SYS_VERSION_MAJOR [0-9]+")
string(REGEX REPLACE "#define JGR_SYS_VERSION_MAJOR ([0-9]+)" "\\1" JGR_SYS_VERSION_MAJOR ${JGR_SYS_VERSION_MAJOR_LINE})

file(STRINGS ${PROJECT_BINARY_DIR}/version.tmp JGR_SYS_VERSION_MINOR_LINE REGEX "JGR_SYS_VERSION_MINOR [0-9]+")
string(REGEX REPLACE "#define JGR_SYS_VERSION_MINOR ([0-9]+)" "\\1" JGR_SYS_VERSION_MINOR ${JGR_SYS_VERSION_MINOR_LINE})

message("jgr_sys version ${JGR_SYS_VERSION_MAJOR}.${JGR_SYS_VERSION_MINOR}")
